# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guis/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaCenterWindow(object):
    def setupUi(self, MediaCenterWindow):
        MediaCenterWindow.setObjectName("MediaCenterWindow")
        MediaCenterWindow.resize(800, 524)
        self.mainLayout = QtWidgets.QVBoxLayout(MediaCenterWindow)
        self.mainLayout.setObjectName("mainLayout")
        self.topNavLayout = QtWidgets.QHBoxLayout()
        self.topNavLayout.setObjectName("topNavLayout")
        self.mediaTab = QtWidgets.QPushButton(MediaCenterWindow)
        self.mediaTab.setMinimumSize(QtCore.QSize(0, 50))
        self.mediaTab.setObjectName("mediaTab")
        self.topNavLayout.addWidget(self.mediaTab)
        self.mapTab = QtWidgets.QPushButton(MediaCenterWindow)
        self.mapTab.setObjectName("mapTab")
        self.topNavLayout.addWidget(self.mapTab)
        self.phoneTab = QtWidgets.QPushButton(MediaCenterWindow)
        self.phoneTab.setObjectName("phoneTab")
        self.topNavLayout.addWidget(self.phoneTab)
        self.settingsTab = QtWidgets.QPushButton(MediaCenterWindow)
        self.settingsTab.setObjectName("settingsTab")
        self.topNavLayout.addWidget(self.settingsTab)
        self.mainLayout.addLayout(self.topNavLayout)
        self.deviceLabel = QtWidgets.QLabel(MediaCenterWindow)
        self.deviceLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deviceLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.deviceLabel.setObjectName("deviceLabel")
        self.mainLayout.addWidget(self.deviceLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(MediaCenterWindow)
        self.label_2.setMinimumSize(QtCore.QSize(200, 200))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(MediaCenterWindow)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.mainLayout.addLayout(self.horizontalLayout_5)
        self.trackTitle = QtWidgets.QLabel(MediaCenterWindow)
        self.trackTitle.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.trackTitle.setIndent(10)
        self.trackTitle.setObjectName("trackTitle")
        self.mainLayout.addWidget(self.trackTitle)
        self.artistName = QtWidgets.QLabel(MediaCenterWindow)
        self.artistName.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.artistName.setIndent(15)
        self.artistName.setObjectName("artistName")
        self.mainLayout.addWidget(self.artistName)
        self.albumName = QtWidgets.QLabel(MediaCenterWindow)
        self.albumName.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.albumName.setIndent(15)
        self.albumName.setObjectName("albumName")
        self.mainLayout.addWidget(self.albumName)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.elapsedTime = QtWidgets.QLabel(MediaCenterWindow)
        self.elapsedTime.setStyleSheet("font-size: 17px;")
        self.elapsedTime.setObjectName("elapsedTime")
        self.progressLayout.addWidget(self.elapsedTime)
        self.progressBar = QtWidgets.QSlider(MediaCenterWindow)
        self.progressBar.setStyleSheet("height: 10px;\n"
                                       "QSlider::groove:horizontal {\n"
                                       "    border: 1px solid #999;\n"
                                       "    height: 6px;\n"
                                       "    background: #2c2c2c;\n"
                                       "    border-radius: 3px;\n"
                                       "}\n"
                                       "\n"
                                       "QSlider::sub-page:horizontal {\n"
                                       "    background: #00bcd4;\n"
                                       "    height: 6px;\n"
                                       "    border-radius: 3px;\n"
                                       "}\n"
                                       "\n"
                                       "QSlider::add-page:horizontal {\n"
                                       "    background: #555;\n"
                                       "    height: 6px;\n"
                                       "    border-radius: 3px;\n"
                                       "}\n"
                                       "\n"
                                       "QSlider::handle:horizontal {\n"
                                       "    background: white;\n"
                                       "    border: 2px solid #00bcd4;\n"
                                       "    width: 14px;\n"
                                       "    height: 14px;\n"
                                       "    margin: -5px 0;\n"
                                       "    border-radius: 7px;\n"
                                       "}")
        self.progressBar.setMaximum(100)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.totalTime = QtWidgets.QLabel(MediaCenterWindow)
        self.totalTime.setStyleSheet("font-size: 17px;")
        self.totalTime.setObjectName("totalTime")
        self.progressLayout.addWidget(self.totalTime)
        self.mainLayout.addLayout(self.progressLayout)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.prevButton = QtWidgets.QPushButton(MediaCenterWindow)
        self.prevButton.setMinimumSize(QtCore.QSize(80, 80))
        self.prevButton.setObjectName("prevButton")
        self.controlLayout.addWidget(self.prevButton)
        self.playPauseButton = QtWidgets.QPushButton(MediaCenterWindow)
        self.playPauseButton.setMinimumSize(QtCore.QSize(100, 100))
        self.playPauseButton.setObjectName("playPauseButton")
        self.controlLayout.addWidget(self.playPauseButton)
        self.nextButton = QtWidgets.QPushButton(MediaCenterWindow)
        self.nextButton.setMinimumSize(QtCore.QSize(80, 80))
        self.nextButton.setObjectName("nextButton")
        self.controlLayout.addWidget(self.nextButton)
        self.mainLayout.addLayout(self.controlLayout)

        self.retranslateUi(MediaCenterWindow)
        QtCore.QMetaObject.connectSlotsByName(MediaCenterWindow)

    def retranslateUi(self, MediaCenterWindow):
        _translate = QtCore.QCoreApplication.translate
        MediaCenterWindow.setWindowTitle(_translate("MediaCenterWindow", "Now Playing"))
        self.mediaTab.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px;"))
        self.mediaTab.setText(_translate("MediaCenterWindow", "🏠 Home"))
        self.mapTab.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px;"))
        self.mapTab.setText(_translate("MediaCenterWindow", "🗺️ Maps"))
        self.phoneTab.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px;"))
        self.phoneTab.setText(_translate("MediaCenterWindow", "🎵 Media"))
        self.settingsTab.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px;"))
        self.settingsTab.setText(_translate("MediaCenterWindow", "⚙️ Settings"))
        self.deviceLabel.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px; font-weight: bold;"))
        self.deviceLabel.setText(_translate("MediaCenterWindow", "🔗 Disconnected"))
        self.label.setText(_translate("MediaCenterWindow", "empty"))
        self.trackTitle.setStyleSheet(_translate("MediaCenterWindow", "font-size: 24px; font-weight: bold;"))
        self.trackTitle.setText(_translate("MediaCenterWindow", "Track Title"))
        self.artistName.setStyleSheet(_translate("MediaCenterWindow", "font-size: 18px;"))
        self.artistName.setText(_translate("MediaCenterWindow", "Artist"))
        self.albumName.setStyleSheet(_translate("MediaCenterWindow", "font-size: 16px; color: gray;"))
        self.albumName.setText(_translate("MediaCenterWindow", "Album"))
        self.elapsedTime.setText(_translate("MediaCenterWindow", "0:00"))
        self.totalTime.setText(_translate("MediaCenterWindow", "3:30"))
        self.prevButton.setStyleSheet(_translate("MediaCenterWindow", "font-size: 24px;"))
        self.prevButton.setText(_translate("MediaCenterWindow", "⏮️"))
        self.playPauseButton.setStyleSheet(_translate("MediaCenterWindow", "font-size: 28px;"))
        self.playPauseButton.setText(_translate("MediaCenterWindow", "▶️"))
        self.nextButton.setStyleSheet(_translate("MediaCenterWindow", "font-size: 24px;"))
        self.nextButton.setText(_translate("MediaCenterWindow", "⏭️"))
